### ISSUE TITLE
Windows 10 support in the future?

### ISSUE THREAD

**Issue by ypan91** [broken-e/DragDropConfirm#22]
Hello broken-e,

Thank you for this great tool, helped me tremendously in the past. As more and more people upgrading to windows 10, would you consider support the new OS in the future?

Appreciate your time!

**Comment by bduffek** [comment]
Is it not working for you?  It should work with Windows 10.

**Comment by ypan91** [comment]
hello @bduffek ,

I found out the root cause of this issue in Windows 10, If I change the display language to English, it's working again perfectly. Previously I was using Chinese as the display language, and I can reproduce the same issue when I switch back to Chinese

**Comment by ypan91** [comment]
when I am in Chinese display language, the symptom is the drag and drop operation will complete without the prompting the "hold up there" message

**Comment by bduffek** [comment]
I apologize but I can't find the directions.  I'll make a quick summary since I don't have much time for many months to do anything with this:

Move and copy by dragging uses an invisible menu, and this checks for that to intercept it and ask confirmation.  The default check is for what Windows 10 uses for English (or at least USA English).

To customize it, you can make the key:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\DragDropConfirm
in the registry.

In there you can make the value "ShowDefaultText" and set it to 1.  (I'm not sure if the specific value matters, I don't have time to verify right now.)

When that value is 1 and you drag to copy or move, it will pop a dialog box up showing what the default command was, and should show you what it needs to be for Chinese.
Make a string value in that DragDropConfirm key called "ItemText" and set that to whatever was displayed in the dialog box.

For example, for English it is:
&Move here

The & is part of it and is required if it appears.

If you want to enable intercepting copies, make ItemText2 and ctrl/drag to see the copy default text, and put it into that ItemText2 value.  Also make a value called WarnOnCopy and set it to 1.

The possible keys to customize are:
ShowDefaultText - DWORD value popping up the default text of the move or copy if no ItemText is defined.
ItemText - String value to search for to identify moves.
ItemText2 - String value to search for to identify copies.
AskTitle - Title bar text of the popup for moves.
AskTitle2 - Title bar test of the popup for copies.
AskDescription - Wording text of the popup for moves.
AskDescription2 - Wording text of the popup for moves.
ShowDirectory - DWORD that can be set to 0 to stop the directory from being shown in the popup box.
WarnOnCopy - DWORD that can be set to 1 to warn on copies as well (when holding Ctrl or dragging across drives/shares).
DefaultButtonOK - DWORD that can be set to 1 or 0 to set the default box of the popup to okay or not.

**Comment by ypan91** [comment]
Thank you so much for the detailed instructions. After I added the registry entry you mentioned, it is now working properly under Chinese display language.

![sreenshot](https://user-images.githubusercontent.com/6531706/71852047-7c33f500-309d-11ea-8eb7-490a8d595c04.png)

**Comment by Stephan-P** [comment]
Registry patch for Dutch language Windows

DragDropConfirm-NL-nl.reg
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\DragDropConfirm]
"ShowDefaultText"=dword:00000001
"ShowDirectory"=dword:00000001
"DefaultButtonOK"=dword:00000000
"WarnOnCopy"=dword:00000001
"ItemText"="Hi&erheen verplaatsen"
"AskTitle"="Waarschuwing"
"AskDescription"="Weet je zeker dat je hierheen wilt verplaatsen?"
"ItemText2"="Hierheen &kopiëren"
"AskTitle2"="Waarschuwing"
"AskDescription2"="Weet je zeker dat je hierheen wilt kopiëren?"

`
