### ISSUE TITLE
Feature: Disable with CTRL-/X & Default button

### ISSUE THREAD

**Issue by leoncvlt** [broken-e/DragDropConfirm#4]
Hi there, I'd like to request some simple improvements - the ability to disable the window when the copy / move is executed via keyboard rather than drag and drop, and being able to choose the default button as OK instead of Cancel. I am not familiar with the implementation flexibility, are those changes feasible?

**Comment by bduffek** [comment]
I know this is an old comment but it's still open:
The first one I'm personally still trying to research. I'm really new to this kind of thing.

The second is trivial to accomplish, though I don't think it would be good for the main project personally.  All it takes is changing MB_DEFBUTTON2 to MB_DEFBUTTON1 in the MessageBoxW call.

**Comment by bduffek** [comment]
I am double posting since a quick search says edits do not trigger notifications.

I believe adding a registry value to choose which button is default is rather trivial and if I remember I'll look into it.  I don't know the proper way to document individual changes for approval though.  I am literally brand new to this site and the entire concept of it, I'm a ways off from getting that far anyway, though.

As far as keyboard shortcuts go, I am starting to get the unfortunate feeling it doesn't differentiate between an invisible menu and the normal one when triggered by the user.  It also fires when right click dragging, _before the user selects an option,_ which looks to be a challenge (if not impossible) to prevent.  Evidence so far suggests even keyboard shortcuts actually invoke the menu and use its corresponding action, but I'm not 100% sure on that.

**Comment by bduffek** [comment]
Okay as the above notification says, adding the option to choose "OK" as the default was trivial.

As I said I spent hours trying to research some way to identify whether the menu is visible or not and thus far I've had no luck.  It really bugs me right click drag pops up the confirmation box.  Hopefully there is some way.  broken-e's knowledge is exponentially greater than mine so it's not a good sign as far as prospects of preventing this side effect.

**Comment by bduffek** [comment]
If you have any idea how do share.  Unfortunately the only way I figured out how to last year would probably conflict with various shell extensions.

**Comment by bduffek** [comment]
The default option was implemented however I'm not sure, barring a completely different way of this being implemented, that it's possible to tell the difference between keyboard shortcuts and dragging.  Because the default button was implemented and the other suggestion seems out of reach I will close this issue.

If anyone knows how differentiating keyboard shortcuts vs. dragging is possible feel free to implement it or create a new issue.
