### ISSUE TITLE
It doesn't work on Windows 10

### ISSUE THREAD

**Issue by avandalen** [broken-e/DragDropConfirm#6]
Can this be solved? I really need this program...

**Comment by veenroid** [comment]
Works on my W10 machine.

**Comment by Arbar1** [comment]
Another acknowledgement that it works on Windows 10 x64 English.

**Comment by Anguel** [comment]
For me it does NOT work on Win 10.

**Comment by bduffek** [comment]
What language are you using?  Currently it specifically checks for the English "&Move here," and will fail for anything else.

**Comment by avandalen** [comment]
Now I use Windows 10 on Netherlands,

**Comment by bduffek** [comment]
Okay what you need to do in order to get it to work is find out what the default "Move here" is called in your Windows language.  There looks to be some code that is meant to pop up a message box for this, but I don't know how to trigger it.  If I figure that out I'll say. My apologies again if this is documented and I missed it.

Creating a key called "DragDropConfirm" in HKEY_LOCAL_MACHINE\Software

In that key you can create string values:
AskTitle
AskDescription
ItemText

ShowDefaultText <- I don't know how to use this to trigger the message box it's intended to pop up.  The AskTitle string value customizes the popup window title, AskDescription does so for the Description, and ItemText is the most important here in that it defines what it looks for.

This works by checking the default menu item for "&Move here" so to get it to work you need to find out the exact text.  Right click drag a file and release it somewhere, and a menu will pop up.  The exact text is important to note.

If there is an underlined letter "&" must go before it.  for example if "h" was underlined the registry value for ItemText would be "Move &here" without the quotation marks.  The M actually does not show an underline in English, so it will probably be the first letter in your language.

Google translate gives me "Verhuis naar hier" but that's probably not right.  IF it were right however you'd set ItemText in the Registry to:
&Verhuis naar hier

If you don't understand what I'm saying let me know what the default text is and what you want the window title and description to say and I'll make a .reg file for you.  I can find the exact text by installing Dutch on my computer when I get home too, assuming that is your language setting (I apologize if it is not).

**Comment by bduffek** [comment]
My apologies for the notification spam, but I believe I read edits do not trigger them.

There is advanced documentation explaining everything here:
http://broken-e.com/dragdropconfirm-instructions

**Comment by bduffek** [comment]
This was likely the text differing from the default.  I will close this issue.  Please open a new one if this persists.
